#!/bin/bash

# Navigate to the application directory (replace with your actual path if different)
cd /home/ec2-user/Podcast-Q-A-Assistant # Amazon Linux default user is ec2-user
# cd /home/ubuntu/your-repo-name # For Ubuntu instances

# Pull the latest code from GitHub
echo "Pulling latest code from GitHub..."
git pull origin master # Adjust 'main' if your default branch is different


# --- Dynamically Generate config.py ---
echo "Generating config.py from secrets..."
# Delete existing config.py if it exists (important for clean updates)
rm -f config.py

# Create config.py with secrets. These environment variables will be passed by GitHub Actions.
echo "# This file is automatically generated by GitHub Actions during deployment." > config.py
echo "# DO NOT ADD THIS FILE TO GIT." >> config.py
echo "" >> config.py

echo "COHERE_API_KEY = \"${COHERE_API_KEY}\"" >> config.py
echo "TAVILY_API_KEY = \"${TAVILY_API_KEY}\"" >> config.py
# Add other sensitive keys here if they exist in your config.py
# echo "ANOTHER_API_KEY = \"${ANOTHER_API_KEY}\"" >> config.py

echo "config.py generated successfully."
# --- End of config.py generation ---


# Install/update Python dependencies (optional, but good for new packages)
echo "Installing/updating Python dependencies..."
pip3 install -r requirements.txt

# Display done installing
echo "DONE INSTALLING"

# Restart the Streamlit app
echo "Restarting Streamlit app..."
# Find and kill any existing streamlit processes on port 8501
sudo lsof -t -i:8501 | xargs -r kill -9
# Start the Streamlit app in the background using nohup
nohup streamlit run app.py --server.port 8501 --server.enableCORS false --server.enableXsrfProtection false > streamlit_app.log 2>&1 &

echo "Deployment complete."